/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-12-11 23:45:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head> \n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Login Page</title>\n");
      out.write("        <style>\n");
      out.write("        \tbody {\n");
      out.write("        \t\tbackground-image: url(\"http://robocode.sourceforge.net/home/robocode_logo_white.jpg\");\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\n");
      out.write("\t\t\tbackground-position: 0 0;\n");
      out.write("\t\t\tbackground-size: cover;\n");
      out.write("\t\t\tcolor: blue;\n");
      out.write("       \t\t}\n");
      out.write("        \tdiv {\n");
      out.write("        \t\tposition : absolute;\n");
      out.write("        \t\ttop : 50%;\n");
      out.write("        \t\tleft:90%;\n");
      out.write("        \t\ttransform:translate(-50%,-50%);\n");
      out.write("       \t\t}\n");
      out.write("       \t\th1.serif {\n");
      out.write("        \t\tcolor : MediumSeaGreen;\n");
      out.write("        \t\ttext-align : left;\n");
      out.write("        \t\tfont-size: 50px;\n");
      out.write("        \t\tfont-family:\"Times New Roman\", Times, serif;\n");
      out.write("        \t}\n");
      out.write("        \th2 {\n");
      out.write("        \t\tcolor : black;\n");
      out.write("        \t\ttext-align:centre;\n");
      out.write("        \t\tfont-family: sans-serif;\n");
      out.write("        \t\tfont-size: 30px;\n");
      out.write("        \t}\n");
      out.write("        \tinput {\n");
      out.write("        \t\tdisplay: block;\n");
      out.write("        \t\twidth: 320px;\n");
      out.write("        \t\theight: 40px;\n");
      out.write("        \t\tpadding: 5px;\n");
      out.write("        \t\tfont-size: 20px;\n");
      out.write("        \t\tfont-family : sans-serif;\n");
      out.write("        \t\tcolor: blue;\n");
      out.write("        \t\toutline: none;\n");
      out.write("        \t\tborder: 1px solid rgba(0,0,0,0.3);\n");
      out.write("        \t\tborder-radius: 5px;\n");
      out.write("        \t\tmargin-bottom: 2px;\n");
      out.write("        \t}\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    \t<h1 class= \"serif\">Login page</h1> \n");
      out.write("    \t<div id=\"login\">\n");
      out.write("    \t<h1>CHECK</h1>\n");
      out.write("        \t<h2>SIGN IN</h2> \n");
      out.write("        \t<form action=\"loginservlet\" method=\"post\">\n");
      out.write("        \t\t<input type=\"text\" name= \"username\" placeholder= \"username\" value=\"\">\n");
      out.write("            \t<br/><input type=\"password\" name= \"password\" placeholder=\"password\" value=\"\"> \n");
      out.write("            \t<br/><input type=\"submit\" value=\"Submit\" > \n");
      out.write("        \t</form> \n");
      out.write("        \t<br/>\n");
      out.write("        \t<h2>REGISTER</h2>\n");
      out.write("        \t<form action=\"UserRegister.jsp\" method=\"post\">\n");
      out.write("            \t<input type=\"text\" name=\"username\" placeholder=\"username\"> \n");
      out.write("            \t<br/><input type=\"password\" name=\"password\" placeholder=\"Password\">\n");
      out.write("            \t<br/><input type=\"password\" name=\"confirm_password\" placeholder=\"Confirm password\">\n");
      out.write("            \t<br/><input type=\"text\" name=\"email\" placeholder=\"email id\">\n");
      out.write("            \t<br/><input type=\"submit\" value=\"Submit\">\n");
      out.write("        \t</form>\n");
      out.write("        </div>\n");
      out.write("    </body> \n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
